name: 打包xzs
on:
#  push:
#    branches:
#      - main
  schedule:
    - cron: '46 12 * * *'


permissions:
  contents: write

jobs:
  npm-build:
    name: npm-build
    runs-on: ubuntu-latest

    steps:
      - name: 读取仓库内容
        uses: actions/checkout@v4
#      - name: 设置 node 版本
#        uses: actions/setup-node@v2
#        with:
#          node-version: '14.21.3'

      - name: 登录DcoekrHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: 构建并推送到 Docker Hub
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: githubops/demo:v4



      - run: >-
          curl -o /dev/null -s -w "%{http_code}\n"
          -H "Content-Type: application/json"
          -d '{"msgtype": "text", "text": {"content": "构建成功，关键词是test。"}}'
          "https://oapi.dingtalk.com/robot/send?access_token=c82ba73f86f5fb9b24c9dc2c8ef6311a26c8ebbaa08e6a413cd8f909fae75f96"
#      - name: 安装依赖&项目打包
#        run: |
#          npm install
#          npm run build
#      - name: 部署
#        uses: JamesIves/github-pages-deploy-action@v4
#        with:
#          branch: gh-pages
#          folder: build






